import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import React from 'react'

import { gql, GraphQLClient } from 'graphql-request';
import { useSpeechSynthesis } from 'react-speech-kit';

import Header from '../components/Header'
import useSWR from 'swr'

export async function getStaticProps() {
  const { getQuizzes } = require("../lib/helpers")
  return {
    props: (await getQuizzes()), revalidate: 1
  }
}

export default function Home(props) {

  const fetcher = (...args) => fetch(...args).then(res => res.json())
  const { data }= useSWR('/api', fetcher, {fallbackData: props, refreshInterval: 3000})
  return (
    <>

      <Head>
        <title>Preview | Spelling App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>
          {data ? data.quizzes[0].quizName : 'Sorry, waiting for the words.'}
          <br/>
          Welcome to <span className="text-blue-600">Spelling with CDS</span>
        </h1>

        <p className={styles.description}>
          Get started by editing the{' '}
          <code className={styles.code}><Link href="/words"><a className="hover:text-blue-600">word list</a></Link></code><br/>
          Or try out this{' '}
          <code className={styles.code}><Link href="/quiz"><a className="hover:text-blue-600">quiz</a></Link></code>
        </p>

        <div className={styles.grid}>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://ryan-james.dev"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built by Ryan James
        </a>
      </footer>
    </>
  )
}
